module.exports = [
  {
    isActive: true,
    age: 20,
    eyeColor: "blue",
    name: "Tricia Torres",
    gender: "female",
    email: "triciatorres@protodyne.com",
  },
  {
    isActive: true,
    age: 24,
    eyeColor: "green",
    name: "Elba Bowen",
    gender: "female",
    email: "elbabowen@protodyne.com",
  },
  {
    isActive: false,
    age: 38,
    eyeColor: "blue",
    name: "Mckenzie Bryan",
    gender: "male",
    email: "mckenziebryan@protodyne.com",
  },
  {
    isActive: true,
    age: 31,
    eyeColor: "brown",
    name: "Violet Boyer",
    gender: "female",
    email: "violetboyer@protodyne.com",
  },
  {
    isActive: true,
    age: 40,
    eyeColor: "blue",
    name: "Jeannie Holland",
    gender: "female",
    email: "jeannieholland@protodyne.com",
  },
  {
    isActive: false,
    age: 20,
    eyeColor: "blue",
    name: "Aisha Lynch",
    gender: "female",
    email: "aishalynch@protodyne.com",
  },
];
